# Generated by Django 4.1.5 on 2023-01-26 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block7', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block7.publisher'),
        ),
        migrations.AddField(
            model_name='genre',
            name='games',
            field=models.ManyToManyField(to='block7.game'),
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(to='block7.game'),
        ),
    ]
