# Generated by Django 4.1.5 on 2023-02-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_remove_user_games_alter_game_id_alter_game_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('games', models.ManyToManyField(to='game.game')),
            ],
        ),
    ]
