# Generated by Django 4.1.5 on 2023-02-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('game', '0002_game_publisher_genre_games_user_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games',
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
