# Generated by Django 4.1.5 on 2023-02-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_games_user_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rate',
            new_name='game',
        ),
    ]
